-- ============================================================================
-- EMS V1 · COMPLETE SCHEMA for Cloudflare D1 (SQLite)
-- ----------------------------------------------------------------------------
-- This is the SQLite counterpart of supabase/ems_complete_schema.sql.
-- Create a D1 database and apply this file with wrangler:
--
--   npx wrangler d1 create ems-d1
--   npx wrangler d1 execute ems-d1 --file=supabase/d1/schema.sql            # local
--   npx wrangler d1 execute ems-d1 --remote --file=supabase/d1/schema.sql  # prod
--
-- Conventions (mirrored by functions/_lib/db.js):
--   · uuid primary keys are TEXT (the driver generates crypto.randomUUID())
--   · bigint identity logs use INTEGER PRIMARY KEY AUTOINCREMENT
--   · booleans are INTEGER (0/1), jsonb / text[] are stored as TEXT (JSON)
--   · dates/timestamps are ISO-8601 TEXT
--   · _sequences backs invoice-number generation (RPC emulation in driver)
--   · business human codes (SUP-/CUS-/EXP-/ITM-) are generated by the driver
-- ============================================================================

-- ----------------------------------------------------------- CORE IDENTITIES
CREATE TABLE IF NOT EXISTS administrators (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  address       TEXT,
  phone         TEXT NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  admin_code    TEXT NOT NULL UNIQUE,
  active        INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ems_owners (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  active        INTEGER NOT NULL DEFAULT 1,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS stores (
  id                   TEXT PRIMARY KEY,
  admin_id             TEXT NOT NULL REFERENCES administrators(id) ON DELETE RESTRICT,
  name                 TEXT NOT NULL,
  address              TEXT,
  phone                TEXT NOT NULL,
  phone2               TEXT,
  email                TEXT,
  website              TEXT,
  shop_code            TEXT NOT NULL UNIQUE,
  category             TEXT NOT NULL DEFAULT 'General Store',
  status               TEXT NOT NULL DEFAULT 'inactive' CHECK(status IN ('active','inactive','read_only')),
  low_stock_threshold  REAL NOT NULL DEFAULT 5,
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_stores_admin ON stores(admin_id);

-- --------------------------------------------------------------- LICENSING
CREATE TABLE IF NOT EXISTS license_plans (
  id                          TEXT PRIMARY KEY,
  title                       TEXT NOT NULL,
  duration_months             INTEGER NOT NULL,
  max_stores                  INTEGER NOT NULL,
  benefits                    TEXT NOT NULL DEFAULT '',
  payment_details             TEXT NOT NULL DEFAULT '',
  price                       REAL NOT NULL DEFAULT 0,
  active                      INTEGER NOT NULL DEFAULT 1,
  connectx_enabled            INTEGER NOT NULL DEFAULT 0,
  connectx_daily_limit        INTEGER NOT NULL DEFAULT 0,
  zudo_enabled                INTEGER NOT NULL DEFAULT 0,
  zudo_daily_limit            INTEGER NOT NULL DEFAULT 0,
  business_health_enabled     INTEGER NOT NULL DEFAULT 0,
  business_health_daily_limit INTEGER NOT NULL DEFAULT 0,
  truebill_enabled            INTEGER NOT NULL DEFAULT 0,
  vaultium_gb                 INTEGER NOT NULL DEFAULT 0,
  created_at                  TEXT NOT NULL,
  updated_at                  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS licenses (
  id                          TEXT PRIMARY KEY,
  admin_id                    TEXT NOT NULL REFERENCES administrators(id) ON DELETE CASCADE,
  store_id                    TEXT REFERENCES stores(id) ON DELETE CASCADE,
  plan_id                     TEXT REFERENCES license_plans(id) ON DELETE SET NULL,
  duration_months             INTEGER NOT NULL,
  amount                      REAL NOT NULL DEFAULT 0,
  max_stores                  INTEGER NOT NULL DEFAULT 1,
  payment_method              TEXT NOT NULL CHECK(payment_method IN ('bkash','nagad','other')),
  payment_number              TEXT NOT NULL,
  transaction_id              TEXT NOT NULL,
  status                      TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','active','expired','rejected')),
  connectx_enabled            INTEGER NOT NULL DEFAULT 0,
  connectx_daily_limit        INTEGER NOT NULL DEFAULT 0,
  zudo_enabled                INTEGER NOT NULL DEFAULT 0,
  zudo_daily_limit            INTEGER NOT NULL DEFAULT 0,
  business_health_enabled     INTEGER NOT NULL DEFAULT 0,
  business_health_daily_limit INTEGER NOT NULL DEFAULT 0,
  truebill_enabled            INTEGER NOT NULL DEFAULT 0,
  vaultium_gb                 INTEGER NOT NULL DEFAULT 0,
  transaction_type            TEXT NOT NULL DEFAULT 'new' CHECK(transaction_type IN ('new','renewal','upgrade','downgrade')),
  starts_at                   TEXT,
  expires_at                  TEXT,
  reviewed_at                 TEXT,
  reviewed_by                 TEXT,
  review_note                 TEXT,
  created_at                  TEXT NOT NULL,
  UNIQUE(payment_method, transaction_id)
);
CREATE INDEX IF NOT EXISTS idx_licenses_status ON licenses(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_licenses_admin_status ON licenses(admin_id, status);
CREATE INDEX IF NOT EXISTS idx_licenses_admin_entitlements ON licenses(admin_id, status, connectx_enabled, starts_at, expires_at);

CREATE TABLE IF NOT EXISTS current_entitlements (
  admin_id                    TEXT PRIMARY KEY REFERENCES administrators(id) ON DELETE CASCADE,
  current_license_id          TEXT REFERENCES licenses(id) ON DELETE SET NULL,
  shop_limit                  INTEGER NOT NULL DEFAULT 0,
  connectx_enabled            INTEGER NOT NULL DEFAULT 0,
  connectx_daily_limit        INTEGER NOT NULL DEFAULT 0,
  zudo_enabled                INTEGER NOT NULL DEFAULT 0,
  zudo_daily_limit            INTEGER NOT NULL DEFAULT 0,
  business_health_enabled     INTEGER NOT NULL DEFAULT 0,
  business_health_daily_limit INTEGER NOT NULL DEFAULT 0,
  truebill_enabled            INTEGER NOT NULL DEFAULT 0,
  vaultium_gb                 INTEGER NOT NULL DEFAULT 0,
  status                      TEXT NOT NULL DEFAULT 'expired' CHECK(status IN ('active','expired')),
  starts_at                   TEXT,
  expires_at                  TEXT,
  updated_at                  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_entitlements_status ON current_entitlements(status, expires_at);

-- ------------------------------------------------------------ SHOP PEOPLE
CREATE TABLE IF NOT EXISTS staff (
  id            TEXT PRIMARY KEY,
  store_id      TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  full_name     TEXT NOT NULL,
  position      TEXT,
  phone         TEXT NOT NULL,
  email         TEXT,
  user_id       TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  basic_salary  REAL NOT NULL DEFAULT 0,
  active        INTEGER NOT NULL DEFAULT 1,
  permissions   TEXT NOT NULL DEFAULT '{}',
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  UNIQUE(store_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_staff_store ON staff(store_id);

CREATE TABLE IF NOT EXISTS suppliers (
  id             TEXT PRIMARY KEY,
  store_id       TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  supplier_code  TEXT NOT NULL UNIQUE,
  name           TEXT NOT NULL,
  address        TEXT,
  phone          TEXT NOT NULL,
  phone2         TEXT,
  email          TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
  id             TEXT PRIMARY KEY,
  store_id       TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  customer_code  TEXT NOT NULL UNIQUE,
  name           TEXT NOT NULL,
  address        TEXT,
  phone          TEXT NOT NULL,
  phone2         TEXT,
  email          TEXT,
  created_at     TEXT NOT NULL,
  updated_at     TEXT NOT NULL
);

-- ------------------------------------------------------------- INVENTORY
CREATE TABLE IF NOT EXISTS inventory_items (
  id           TEXT PRIMARY KEY,
  store_id     TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  item_code    TEXT NOT NULL,
  description  TEXT NOT NULL,
  unit         TEXT NOT NULL,
  sale_price   REAL NOT NULL DEFAULT 0,
  total_stock  REAL NOT NULL DEFAULT 0,
  active       INTEGER NOT NULL DEFAULT 1,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL,
  UNIQUE(store_id, item_code)
);
CREATE INDEX IF NOT EXISTS idx_inventory_store ON inventory_items(store_id);

-- -------------------------------------------------------------- INVOICES
CREATE TABLE IF NOT EXISTS invoices (
  id                    TEXT PRIMARY KEY,
  store_id              TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  kind                  TEXT NOT NULL CHECK(kind IN ('purchase','sale')),
  invoice_number        TEXT NOT NULL,
  party_id              TEXT,
  invoice_date          TEXT NOT NULL,
  payment_method        TEXT NOT NULL DEFAULT 'cash' CHECK(payment_method IN ('cash','bank','bkash','nagad','other')),
  transaction_id        TEXT,
  notes                 TEXT,
  subtotal              REAL NOT NULL DEFAULT 0,
  tax_percent           REAL NOT NULL DEFAULT 0,
  discount              REAL NOT NULL DEFAULT 0,
  tax_amount            REAL NOT NULL DEFAULT 0,
  paid_amount           REAL NOT NULL DEFAULT 0,
  total_due             REAL NOT NULL DEFAULT 0,
  created_by            TEXT,
  verification_token    TEXT,
  custom_party_name     TEXT,
  custom_party_address  TEXT,
  custom_party_phone    TEXT,
  created_at            TEXT NOT NULL,
  updated_at            TEXT NOT NULL,
  UNIQUE(store_id, invoice_number)
);
CREATE INDEX IF NOT EXISTS idx_invoices_store_kind_date ON invoices(store_id, kind, invoice_date DESC);
CREATE UNIQUE INDEX IF NOT EXISTS invoices_verification_token_uq ON invoices(verification_token);

CREATE TABLE IF NOT EXISTS invoice_lines (
  id           TEXT PRIMARY KEY,
  invoice_id   TEXT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  item_id      TEXT NOT NULL REFERENCES inventory_items(id) ON DELETE RESTRICT,
  quantity     REAL NOT NULL,
  unit_price   REAL NOT NULL,
  line_total   REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
  id            TEXT PRIMARY KEY,
  store_id      TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  expense_code  TEXT NOT NULL UNIQUE,
  expense_date  TEXT NOT NULL,
  details       TEXT NOT NULL,
  total         REAL NOT NULL,
  paid          REAL NOT NULL DEFAULT 0,
  due           REAL GENERATED ALWAYS AS (total - paid) STORED,
  note          TEXT,
  created_by    TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS attendance (
  id               TEXT PRIMARY KEY,
  store_id         TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  staff_id         TEXT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  attendance_date  TEXT NOT NULL,
  status           TEXT NOT NULL CHECK(status IN ('present','absent')),
  note             TEXT,
  recorded_by      TEXT,
  created_at       TEXT NOT NULL,
  UNIQUE(staff_id, attendance_date)
);

CREATE TABLE IF NOT EXISTS device_logins (
  id                 TEXT PRIMARY KEY,
  store_id           TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  staff_id           TEXT REFERENCES staff(id) ON DELETE SET NULL,
  device_fingerprint TEXT NOT NULL,
  user_agent         TEXT,
  last_seen_at       TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  UNIQUE(store_id, device_fingerprint)
);
CREATE INDEX IF NOT EXISTS idx_device_logins_store_seen ON device_logins(store_id, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS due_recoveries (
  id             TEXT PRIMARY KEY,
  store_id       TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  source_type    TEXT NOT NULL CHECK(source_type IN ('sale','purchase','expense')),
  source_id      TEXT NOT NULL,
  amount         REAL NOT NULL,
  note           TEXT,
  payment_method TEXT CHECK(payment_method IN ('cash','bkash','nagad','bank','other')),
  transaction_id TEXT,
  recovered_by   TEXT,
  created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_due_recoveries_store_source ON due_recoveries(store_id, source_type, source_id, created_at DESC);

-- ----------------------------------------------------- SALARY
CREATE TABLE IF NOT EXISTS staff_salary_invoices (
  id                TEXT PRIMARY KEY,
  store_id          TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  staff_id          TEXT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
  salary_month      TEXT NOT NULL,
  invoice_type      TEXT NOT NULL DEFAULT 'current' CHECK(invoice_type IN ('current','due','advance')),
  base_amount       REAL NOT NULL DEFAULT 0,
  attendance_based  INTEGER NOT NULL DEFAULT 0,
  present_days      INTEGER,
  total_days        INTEGER,
  incentive         REAL NOT NULL DEFAULT 0,
  bonus             REAL NOT NULL DEFAULT 0,
  fine              REAL NOT NULL DEFAULT 0,
  other_deduction   REAL NOT NULL DEFAULT 0,
  add_outstanding   INTEGER NOT NULL DEFAULT 0,
  cut_advance       INTEGER NOT NULL DEFAULT 0,
  total             REAL NOT NULL DEFAULT 0,
  paid              REAL NOT NULL DEFAULT 0,
  due               REAL GENERATED ALWAYS AS (total - paid) STORED,
  note              TEXT,
  created_by        TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_salary_store_date ON staff_salary_invoices(store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_salary_staff ON staff_salary_invoices(staff_id);

-- ----------------------------------------------------- LOGS
CREATE TABLE IF NOT EXISTS activity_logs (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  store_id     TEXT REFERENCES stores(id) ON DELETE CASCADE,
  actor_type   TEXT NOT NULL,
  actor_id     TEXT,
  action       TEXT NOT NULL,
  entity_type  TEXT,
  entity_id    TEXT,
  metadata     TEXT NOT NULL DEFAULT '{}',
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_activity_store_date ON activity_logs(store_id, created_at DESC);

CREATE TABLE IF NOT EXISTS error_logs (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  store_id    TEXT REFERENCES stores(id) ON DELETE CASCADE,
  actor_id    TEXT,
  message     TEXT NOT NULL,
  context     TEXT NOT NULL DEFAULT '{}',
  created_at  TEXT NOT NULL
);

-- --------------------------------------------- PLATFORM CONTROL
CREATE TABLE IF NOT EXISTS platform_settings (
  setting_key    TEXT PRIMARY KEY,
  setting_value  TEXT NOT NULL,
  updated_by     TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  updated_at     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS platform_activity_logs (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  owner_id     TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  action       TEXT NOT NULL,
  entity_type  TEXT,
  entity_id    TEXT,
  metadata     TEXT NOT NULL DEFAULT '{}',
  created_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS helpdesk_messages (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  admin_id       TEXT NOT NULL REFERENCES administrators(id) ON DELETE CASCADE,
  sender_type    TEXT NOT NULL CHECK(sender_type IN ('admin','owner')),
  content        TEXT NOT NULL,
  read_by_admin  INTEGER NOT NULL DEFAULT 1,
  read_by_owner  INTEGER NOT NULL DEFAULT 1,
  created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_helpdesk_admin ON helpdesk_messages(admin_id, created_at ASC);
CREATE INDEX IF NOT EXISTS idx_helpdesk_admin_unread ON helpdesk_messages(admin_id, sender_type, read_by_admin);

-- --------------------------------------------------------- CONNECTX
CREATE TABLE IF NOT EXISTS connectx_settings (
  id                  INTEGER PRIMARY KEY CHECK (id = 1),
  provider            TEXT NOT NULL DEFAULT 'brevo_api',
  from_name           TEXT NOT NULL DEFAULT 'EMS ConnectX',
  from_email          TEXT NOT NULL,
  reply_to            TEXT,
  global_daily_limit  INTEGER NOT NULL DEFAULT 300,
  enabled             INTEGER NOT NULL DEFAULT 0,
  updated_by          TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  updated_at          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS connectx_messages (
  id                   TEXT PRIMARY KEY,
  store_id             TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  user_id              TEXT,
  recipient_type       TEXT NOT NULL CHECK(recipient_type IN ('customer','supplier','staff','administrator','manual')),
  recipient_id         TEXT,
  invoice_id           TEXT REFERENCES invoices(id) ON DELETE SET NULL,
  from_email           TEXT NOT NULL,
  to_emails            TEXT NOT NULL DEFAULT '[]',
  cc_emails            TEXT NOT NULL DEFAULT '[]',
  bcc_emails           TEXT NOT NULL DEFAULT '[]',
  subject              TEXT NOT NULL,
  custom_body          TEXT,
  body_html            TEXT NOT NULL,
  provider             TEXT NOT NULL,
  provider_message_id  TEXT,
  status               TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','sending','sent','failed')),
  error_message        TEXT,
  idempotency_key      TEXT NOT NULL,
  shop_deleted_at      TEXT,
  shop_deleted_by      TEXT,
  sent_at              TEXT,
  created_at           TEXT NOT NULL,
  UNIQUE(store_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_connectx_store_created ON connectx_messages(store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_connectx_store_visible ON connectx_messages(store_id, shop_deleted_at, created_at DESC);

CREATE TABLE IF NOT EXISTS connectx_sms_messages (
  id              TEXT PRIMARY KEY,
  store_id        TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  user_id         TEXT,
  recipient_type  TEXT NOT NULL CHECK(recipient_type IN ('customer','supplier','staff','manual')),
  recipient_id    TEXT,
  recipient_name  TEXT,
  to_phone        TEXT NOT NULL,
  message_type    TEXT NOT NULL,
  invoice_id      TEXT,
  message_body    TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'queued' CHECK(status IN ('queued','sending','sent','failed')),
  device_id       TEXT,
  attempts        INTEGER NOT NULL DEFAULT 0,
  error_message   TEXT,
  created_at      TEXT NOT NULL,
  sent_at         TEXT
);
CREATE INDEX IF NOT EXISTS idx_cx_sms_store_created ON connectx_sms_messages(store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cx_sms_store_status ON connectx_sms_messages(store_id, status);

-- -------------------------------------------------------------- ZUDO
CREATE TABLE IF NOT EXISTS zudo_settings (
  id                  INTEGER PRIMARY KEY CHECK (id = 1),
  enabled             INTEGER NOT NULL DEFAULT 0,
  model               TEXT NOT NULL DEFAULT '@cf/meta/llama-3.2-3b-instruct',
  global_daily_limit  INTEGER NOT NULL DEFAULT 500,
  updated_by          TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  updated_at          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS zudo_conversations (
  id               TEXT PRIMARY KEY,
  store_id         TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  user_id          TEXT NOT NULL,
  title            TEXT NOT NULL DEFAULT 'New conversation',
  shop_deleted_at  TEXT,
  shop_deleted_by  TEXT,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_zudo_convs_user ON zudo_conversations(store_id, user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_zudo_convs_visible ON zudo_conversations(store_id, user_id, shop_deleted_at, updated_at DESC);

CREATE TABLE IF NOT EXISTS zudo_messages (
  id               TEXT PRIMARY KEY,
  conversation_id  TEXT NOT NULL REFERENCES zudo_conversations(id) ON DELETE CASCADE,
  store_id         TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  user_id          TEXT NOT NULL,
  role             TEXT NOT NULL CHECK(role IN ('user','assistant')),
  content          TEXT NOT NULL,
  created_at       TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_zudo_msgs_conversation ON zudo_messages(conversation_id, created_at);

-- ----------------------------------------------- BUSINESS AI HEALTH
CREATE TABLE IF NOT EXISTS business_health_settings (
  id                  INTEGER PRIMARY KEY CHECK (id = 1),
  enabled             INTEGER NOT NULL DEFAULT 0,
  model               TEXT NOT NULL DEFAULT '@cf/meta/llama-3.2-3b-instruct',
  global_daily_limit  INTEGER NOT NULL DEFAULT 100,
  updated_by          TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  updated_at          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS business_health_reports (
  id           TEXT PRIMARY KEY,
  store_id     TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  user_id      TEXT NOT NULL,
  start_date   TEXT NOT NULL,
  end_date     TEXT NOT NULL,
  score        INTEGER NOT NULL,
  snapshot     TEXT NOT NULL DEFAULT '{}',
  insights     TEXT NOT NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_bh_reports_store_date ON business_health_reports(store_id, created_at DESC);

-- -------------------------------------------------------- PUBLIC SITE
CREATE TABLE IF NOT EXISTS public_pages (
  slug               TEXT PRIMARY KEY CHECK(slug IN ('about','terms','contact')),
  title              TEXT NOT NULL,
  body               TEXT NOT NULL DEFAULT '',
  hero_image_prompt  TEXT,
  updated_by         TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  updated_at         TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS blog_posts (
  id               TEXT PRIMARY KEY,
  title            TEXT NOT NULL,
  slug             TEXT NOT NULL UNIQUE,
  excerpt          TEXT,
  body             TEXT NOT NULL,
  cover_image_url  TEXT,
  published        INTEGER NOT NULL DEFAULT 0,
  published_at     TEXT,
  created_by       TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS contact_messages (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  email       TEXT NOT NULL,
  phone       TEXT,
  subject     TEXT,
  message     TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'new' CHECK(status IN ('new','read','closed')),
  created_at  TEXT NOT NULL
);

-- ----------------------------------------------------------- TRUEBILL
CREATE TABLE IF NOT EXISTS truebill_scans (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  store_id        TEXT REFERENCES stores(id) ON DELETE SET NULL,
  invoice_id      TEXT,
  invoice_number  TEXT NOT NULL,
  invoice_kind    TEXT,
  scanned_at      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ip_address      TEXT,
  user_agent      TEXT
);
CREATE INDEX IF NOT EXISTS idx_truebill_scanned ON truebill_scans(scanned_at DESC);

-- ------------------------------------------------------- ADD-ONS
CREATE TABLE IF NOT EXISTS addon_settings (
  addon_key        TEXT PRIMARY KEY CHECK(addon_key IN ('connectx','zudo','business_health','truebill','vaultium')),
  enabled          INTEGER NOT NULL DEFAULT 0,
  title            TEXT NOT NULL,
  details          TEXT NOT NULL DEFAULT '',
  unit_price       REAL NOT NULL DEFAULT 0,
  min_days         INTEGER NOT NULL DEFAULT 1,
  max_days         INTEGER NOT NULL DEFAULT 365,
  min_daily_limit  INTEGER NOT NULL DEFAULT 1,
  max_daily_limit  INTEGER NOT NULL DEFAULT 1000,
  payment_info     TEXT NOT NULL DEFAULT '',
  image_url        TEXT,
  url              TEXT,
  updated_by       TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  updated_at       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS addon_purchases (
  id               TEXT PRIMARY KEY,
  admin_id         TEXT NOT NULL REFERENCES administrators(id) ON DELETE CASCADE,
  addon_key        TEXT NOT NULL CHECK(addon_key IN ('connectx','zudo','business_health','truebill','vaultium')),
  validity_days    INTEGER NOT NULL,
  daily_limit      INTEGER NOT NULL,
  unit_price       REAL NOT NULL,
  amount           REAL NOT NULL,
  coupon_code      TEXT,
  discount_amount  REAL NOT NULL DEFAULT 0,
  payment_method   TEXT NOT NULL CHECK(payment_method IN ('cash','bank','bkash','nagad','other')),
  payment_number   TEXT NOT NULL,
  transaction_id   TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','active','rejected','expired')),
  starts_at        TEXT,
  expires_at       TEXT,
  reviewed_at      TEXT,
  review_note      TEXT,
  created_at       TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_addon_purchases_admin_key ON addon_purchases(admin_id, addon_key, status, expires_at DESC);

CREATE TABLE IF NOT EXISTS addon_checkout_settings (
  id            INTEGER PRIMARY KEY CHECK (id = 1),
  payment_info  TEXT NOT NULL DEFAULT '',
  updated_by    TEXT REFERENCES ems_owners(id) ON DELETE SET NULL,
  updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS addon_coupons (
  code         TEXT PRIMARY KEY,
  percent_off  REAL NOT NULL,
  active       INTEGER NOT NULL DEFAULT 1,
  expires_at   TEXT,
  created_at   TEXT NOT NULL
);

-- ------------------------------------------------------------ VAULTIUM
CREATE TABLE IF NOT EXISTS vaultium_files (
  id             TEXT PRIMARY KEY,
  admin_id       TEXT NOT NULL REFERENCES administrators(id) ON DELETE CASCADE,
  store_id       TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  invoice_id     TEXT REFERENCES invoices(id) ON DELETE SET NULL,
  invoice_number TEXT,
  expense_id     TEXT REFERENCES expenses(id) ON DELETE SET NULL,
  expense_code   TEXT,
  filename       TEXT NOT NULL,
  content_type   TEXT,
  size_bytes     INTEGER NOT NULL DEFAULT 0,
  r2_key         TEXT NOT NULL,
  uploaded_by    TEXT,
  created_at     TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vaultium_store_date ON vaultium_files(store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vaultium_admin ON vaultium_files(admin_id);
CREATE INDEX IF NOT EXISTS idx_vaultium_invoice ON vaultium_files(invoice_id);
CREATE INDEX IF NOT EXISTS idx_vaultium_expense ON vaultium_files(expense_id);

-- ---------------------------------------------------- RETURNS & REFUNDS
CREATE TABLE IF NOT EXISTS returns (
  id                  TEXT PRIMARY KEY,
  store_id            TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  invoice_id          TEXT NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,
  return_number       TEXT NOT NULL,
  customer_id         TEXT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name       TEXT,
  return_date         TEXT NOT NULL DEFAULT (date('now')),
  subtotal            NUMERIC NOT NULL DEFAULT 0,
  tax_amount          NUMERIC NOT NULL DEFAULT 0,
  discount_amount     NUMERIC NOT NULL DEFAULT 0,
  penalty_amount      NUMERIC NOT NULL DEFAULT 0,
  total_return_amount NUMERIC NOT NULL DEFAULT 0,
  refunded_amount     NUMERIC NOT NULL DEFAULT 0,
  refund_method       TEXT DEFAULT 'cash',
  transaction_id      TEXT,
  status              TEXT NOT NULL DEFAULT 'refunded' CHECK(status IN ('pending_refund','partially_refunded','refunded')),
  notes               TEXT,
  created_by          TEXT,
  verification_token  TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(store_id, return_number)
);

CREATE INDEX IF NOT EXISTS idx_returns_store ON returns(store_id);
CREATE INDEX IF NOT EXISTS idx_returns_invoice ON returns(invoice_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_returns_verification_token ON returns(verification_token);

CREATE TABLE IF NOT EXISTS return_items (
  id                  TEXT PRIMARY KEY,
  return_id           TEXT NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  invoice_line_id     TEXT REFERENCES invoice_lines(id) ON DELETE SET NULL,
  item_id             TEXT NOT NULL REFERENCES inventory_items(id) ON DELETE RESTRICT,
  quantity            NUMERIC NOT NULL CHECK(quantity > 0),
  unit_price          NUMERIC NOT NULL CHECK(unit_price >= 0),
  tax_percent         NUMERIC NOT NULL DEFAULT 0,
  tax_amount          NUMERIC NOT NULL DEFAULT 0,
  discount            NUMERIC NOT NULL DEFAULT 0,
  penalty             NUMERIC NOT NULL DEFAULT 0,
  return_amount       NUMERIC NOT NULL CHECK(return_amount >= 0),
  reason              TEXT NOT NULL CHECK(reason IN ('Customer Changed Mind','Defective','Wrong Product','Damaged','Wrong Specification','Other')),
  reason_note         TEXT,
  condition           TEXT NOT NULL CHECK(condition IN ('Sellable','Damaged','Defective','Warranty')),
  imei_serial         TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_return_items_return ON return_items(return_id);
CREATE INDEX IF NOT EXISTS idx_return_items_item ON return_items(item_id);

CREATE TABLE IF NOT EXISTS exchanges (
  id                  TEXT PRIMARY KEY,
  store_id            TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  invoice_id          TEXT NOT NULL REFERENCES invoices(id) ON DELETE RESTRICT,
  exchange_number     TEXT NOT NULL,
  customer_id         TEXT REFERENCES customers(id) ON DELETE SET NULL,
  customer_name       TEXT,
  exchange_date       TEXT NOT NULL DEFAULT (date('now')),
  returned_total      NUMERIC NOT NULL DEFAULT 0,
  new_items_subtotal  NUMERIC NOT NULL DEFAULT 0,
  new_items_tax       NUMERIC NOT NULL DEFAULT 0,
  new_items_discount  NUMERIC NOT NULL DEFAULT 0,
  new_items_total     NUMERIC NOT NULL DEFAULT 0,
  difference_amount   NUMERIC NOT NULL DEFAULT 0,
  action_type         TEXT NOT NULL DEFAULT 'even' CHECK(action_type IN ('payment','refund','even')),
  payment_method      TEXT CHECK(payment_method IN ('cash','bank','bkash','nagad','other','none')) DEFAULT 'none',
  transaction_id      TEXT,
  status              TEXT NOT NULL DEFAULT 'completed' CHECK(status IN ('completed','cancelled')),
  notes               TEXT,
  created_by          TEXT,
  verification_token  TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at          TEXT NOT NULL DEFAULT (datetime('now')),
  UNIQUE(store_id, exchange_number)
);

CREATE INDEX IF NOT EXISTS idx_exchanges_store ON exchanges(store_id);
CREATE INDEX IF NOT EXISTS idx_exchanges_invoice ON exchanges(invoice_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_exchanges_verification_token ON exchanges(verification_token);

CREATE TABLE IF NOT EXISTS exchange_items (
  id                  TEXT PRIMARY KEY,
  exchange_id         TEXT NOT NULL REFERENCES exchanges(id) ON DELETE CASCADE,
  item_type           TEXT NOT NULL CHECK(item_type IN ('returned','new')),
  invoice_line_id     TEXT REFERENCES invoice_lines(id) ON DELETE SET NULL,
  item_id             TEXT NOT NULL REFERENCES inventory_items(id) ON DELETE RESTRICT,
  quantity            NUMERIC NOT NULL CHECK(quantity > 0),
  unit_price          NUMERIC NOT NULL CHECK(unit_price >= 0),
  tax_percent         NUMERIC NOT NULL DEFAULT 0,
  tax_amount          NUMERIC NOT NULL DEFAULT 0,
  discount            NUMERIC NOT NULL DEFAULT 0,
  total_amount        NUMERIC NOT NULL CHECK(total_amount >= 0),
  reason              TEXT,
  reason_note         TEXT,
  condition           TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_exchange_items_exchange ON exchange_items(exchange_id);
CREATE INDEX IF NOT EXISTS idx_exchange_items_item ON exchange_items(item_id);

CREATE TABLE IF NOT EXISTS inventory_stock_movements (
  id                  TEXT PRIMARY KEY,
  store_id            TEXT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
  item_id             TEXT NOT NULL REFERENCES inventory_items(id) ON DELETE RESTRICT,
  return_id           TEXT REFERENCES returns(id) ON DELETE CASCADE,
  exchange_id         TEXT REFERENCES exchanges(id) ON DELETE CASCADE,
  movement_type       TEXT NOT NULL,
  quantity            NUMERIC NOT NULL,
  stock_before        NUMERIC,
  stock_after         NUMERIC,
  condition           TEXT NOT NULL,
  notes               TEXT,
  created_by          TEXT,
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_inv_mov_store ON inventory_stock_movements(store_id);
CREATE INDEX IF NOT EXISTS idx_inv_mov_item ON inventory_stock_movements(item_id);
CREATE INDEX IF NOT EXISTS idx_inv_mov_return ON inventory_stock_movements(return_id);
CREATE INDEX IF NOT EXISTS idx_inv_mov_exchange ON inventory_stock_movements(exchange_id);

-- -------------------------------------- DRIVER-ONLY SEQUENCE TABLE (D1)
CREATE TABLE IF NOT EXISTS _sequences (
  name   TEXT PRIMARY KEY,
  value  INTEGER NOT NULL DEFAULT 0
);

-- ============================================================================
-- SEED DEFAULTS (idempotent)
-- ============================================================================
INSERT INTO platform_settings(setting_key, setting_value, updated_at)
VALUES ('branding', '{"product_name":"EMS V1","powered_by":"DoxTox","website_name":"EMS V1","public_base_url":""}', strftime('%Y-%m-%dT%H:%M:%fZ','now'))
ON CONFLICT(setting_key) DO NOTHING;

INSERT INTO platform_settings(setting_key, setting_value, updated_at)
VALUES ('theme', '{"primary":"#3975eb","secondary":"#2759ce","accent":"#8b5cf6","page_background":"#f4f7fb","main_text":"#172b4d","secondary_text":"#62748a","border":"#dbe4ee","sidebar_background":"#eaf5ff","sidebar_text":"#1e3a5f","sidebar_active":"#d7eaff","success":"#16803a","warning":"#b7791f","error":"#c62828","info":"#1769e0","glass_tint":"#eaf5ff","glass_opacity":"0.72","glass_blur":"18","glass_border_opacity":"0.82","classic_ink":"#172536","classic_navy":"#173b59","classic_navy_deep":"#102d45","classic_slate":"#607184","classic_cream":"#f7f4ee","classic_paper":"#fffdfa","classic_line":"#e2ddd3","classic_teal":"#2f806f","classic_teal_dark":"#236456","classic_gold":"#c8954e","classic_red":"#b64f4b"}', strftime('%Y-%m-%dT%H:%M:%fZ','now'))
ON CONFLICT(setting_key) DO NOTHING;

INSERT INTO public_pages(slug, title, body, updated_at) VALUES
  ('about','About EMS V1','', strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('terms','Terms & Conditions','', strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('contact','Contact Us','', strftime('%Y-%m-%dT%H:%M:%fZ','now'))
ON CONFLICT(slug) DO NOTHING;

INSERT INTO addon_checkout_settings(id, payment_info, updated_at)
VALUES (1, '', strftime('%Y-%m-%dT%H:%M:%fZ','now'))
ON CONFLICT(id) DO NOTHING;

INSERT INTO addon_settings(addon_key, enabled, title, details, unit_price, min_days, max_days, min_daily_limit, max_daily_limit, updated_at) VALUES
  ('connectx',       0, 'ConnectX',           'Send business emails through EMS.',                                              2,  7, 365, 10, 500, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('zudo',           0, 'Zudo AI',            'Read-only AI assistant for your shop.',                                          2,  7, 365, 10, 500, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('business_health',0, 'AI Business Health', 'Business-health reports from your data.',                                       2,  7, 365,  1,  50, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('truebill',       0, 'TrueBill',           'Put a scannable QR code on every invoice so customers can verify authenticity.', 2, 30, 365,  1,   1, strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  ('vaultium',       0, 'Vaultium',           'Secure cloud file storage for invoices and expense documents (GB).',             0,  1, 365,  1, 100, strftime('%Y-%m-%dT%H:%M:%fZ','now'))
ON CONFLICT(addon_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS app_store_apps (
  id                   TEXT PRIMARY KEY,
  package_name         TEXT NOT NULL,
  title                TEXT NOT NULL,
  description          TEXT NOT NULL DEFAULT '',
  version              TEXT NOT NULL DEFAULT '1.0.0',
  version_code         INTEGER NOT NULL DEFAULT 1,
  icon_url             TEXT NOT NULL DEFAULT '',
  apk_url              TEXT NOT NULL DEFAULT '',
  apk_size_bytes       INTEGER NOT NULL DEFAULT 0,
  apk_filename         TEXT NOT NULL DEFAULT '',
  r2_key               TEXT,
  mandatory            INTEGER NOT NULL DEFAULT 0,
  release_notes        TEXT NOT NULL DEFAULT '',
  published            INTEGER NOT NULL DEFAULT 1,
  created_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at           TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_app_store_pkg ON app_store_apps(package_name);
CREATE INDEX IF NOT EXISTS idx_app_store_pub ON app_store_apps(published, created_at DESC);

INSERT INTO zudo_settings(id, updated_at) VALUES (1, strftime('%Y-%m-%dT%H:%M:%fZ','now')) ON CONFLICT(id) DO NOTHING;
INSERT INTO business_health_settings(id, updated_at) VALUES (1, strftime('%Y-%m-%dT%H:%M:%fZ','now')) ON CONFLICT(id) DO NOTHING;
-- End of EMS V1 D1 schema.
